# Generated by Django 5.1.6 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_doctor_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1', models.DateTimeField(auto_now=True)),
                ('slot_2', models.DateTimeField(auto_now=True)),
                ('slot_3', models.DateTimeField(auto_now=True)),
                ('slot_4', models.DateTimeField(auto_now=True)),
                ('slot_5', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
