# Generated by Django 5.1.6 on 2025-03-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot_1',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_2',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_3',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_4',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot_5',
        ),
    ]
