# Generated by Django 5.1.6 on 2025-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_remove_slot_slot_1_remove_slot_slot_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot1',
            field=models.DateField(auto_now=True),
        ),
    ]
