# Generated by Django 5.1.6 on 2025-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_slot_slot1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot1',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
