# Generated by Django 5.1.6 on 2025-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_slot_slot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot3',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot4',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot5',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
