# Generated by Django 5.1.6 on 2025-03-05 09:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_slot_slot2_slot_slot3_slot_slot4_slot_slot5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot3',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot4',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot5',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot1',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 15, 9, 6, 770605)),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.patient')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.slot')),
            ],
        ),
    ]
