# Generated by Django 5.1.6 on 2025-03-05 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_remove_slot_slot2_remove_slot_slot3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot1',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 3, 10)),
        ),
    ]
