# Generated by Django 5.1.6 on 2025-03-05 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_slot_slot1'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot2',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 3, 10)),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot3',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 3, 10)),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot4',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 3, 10)),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot5',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 3, 10)),
        ),
    ]
