# Generated by Django 5.1.6 on 2025-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_slot_slot2_slot_slot3_slot_slot4_slot_slot5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot2',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot3',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot4',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='slot5',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot1',
            field=models.DateTimeField(),
        ),
    ]
