# Generated by Django 5.1.6 on 2025-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_remove_slot_slot2_remove_slot_slot3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='duration',
            field=models.CharField(choices=[('AM', 'PM')], default='AM', max_length=2),
        ),
    ]
