# Generated by Django 5.1.6 on 2025-03-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_slot_duration'),
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_created', to='App2.receptionist'),
        ),
    ]
