# Generated by Django 5.1.6 on 2025-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_schedule_created_at_schedule_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
